package com.example.QualityManagementSystem.dto;

import com.example.QualityManagementSystem.model.Role;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class RegisterRequest {
    private String username; // email address
    private String fullName;
    private Role role;
    // Note: password is not included as it will be generated by admin
}
